### ISSUE TITLE
Use lowercase in keys

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-doi#13]
Prefer not using any capitalization in keys. issn over ISSN.

_Originally posted by @opoudjis in https://github.com/relaton/relaton-doi/issues/10#issuecomment-1382707031_

**Comment by opoudjis** [comment]
@ronaldtse this breaks things for me. Now I have to do case insensitive detection.

**Comment by ronaldtse** [comment]
@opoudjis this is a one off change, and Metanorma is meant to access this information via Relaton methods. Is this not the case?

**Comment by opoudjis** [comment]
No, it is not the case, and with ISSN being a value and not a key, relaton methods (which I cannot use in downstream nokogiri processing) are irrelevant. This will break things.
