### ISSUE TITLE
Integrate into relaton-cli to allow access via unified interface

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-doi#5]
The Relaton-DOI gem should be useable through Relaton-CLI.

The way to differentiate against different types is through the `doi:...` prefix.

e.g.
```sh
$ relaton fetch doi:10.17487/RFC0001
=> serialization of RelatonIetf::IetfBibliographicItem:0x00007f9c8143d058...
```

**Comment by opoudjis** [comment]
Recall that all relaton fetches are premised on a distinctive prefix by relaton gem; e.g. all relaton-iso calls are prefixed by ISO. The expectation is that `doi:` is recognised as the distinctive prefix of relaton-doi requests, and the `doi:` prefix will be stripped before (or, per https://github.com/relaton/relaton-doi/issues/4, after) passing it to `RelatonDoi::Crossref`.
